class ImageResources {
  static const images = 'asset/login_page_logo/';
  static const image = 'asset/home_page_image/';
  static const drawerimage = 'asset/home_page_image/drawer_image/';
  static const floatingicon = 'asset/home_page_image/floating_icon/';
  static const locationicon = 'asset/home_page_image/location_icon/';
  static const categorypageicon = 'asset/category_page_icon/';

  static const splashscrrenLogo = 'asset/Screen Shot 2021-04-07 at 8.09 1.png';
  static const lookPrior = 'asset/Group 10219.svg';

  static const loginLogo = '${images}login_logo.png';
  static const youricon = '${images}User.svg';
  static const emailicon = '${images}email.svg';
  static const phoneicon = '${images}Call.svg';
  static const passwordicon = '${images}Lock.svg';
  static const confmpasswordicon = '${images}Lock.svg';
  static const fackbookicon = '${images}Group.svg';
  static const appleicon = '${images}apple.svg';
  static const alertdialogimg = '${image}AlertDialogimg.jpg';
  static const looklogo = '${image}looklogo.png';
  static const drawerimg = '${image}drawerimg.svg';
  static const notificationimg = '${image}notificationimg.svg';
  static const layoutlogo = '${image}layoutlogo.svg';
  static const locationlogo = '${image}locationlogo.svg';
  static const userlogo = '${drawerimage}userlogo.svg';
  static const arrowicon = '${drawerimage}Arrow - Right.svg';
  static const category = '${drawerimage}Category.svg';
  static const camera = '${drawerimage}Camera.svg';
  static const user = '${drawerimage}3 User.svg';
  static const help = '${drawerimage}help.svg';
  static const space = '${drawerimage}space.svg';
  static const ads = '${drawerimage}ads.svg';
  static const backarow = '${drawerimage}backarow.svg';
  static const search = '${drawerimage}Search.svg';
  static const car = '${image}car.svg';
  static const smartphone = '${image}smartphone.svg';
  static const hotel = '${image}hotel.svg';
  static const carimag = '${image}carimag.png';
  static const comimg = '${image}comimg.png';
  static const share = '${image}share.svg';
  static const likeicon = '${image}likeicon.svg';
  static const trophyicon = '${image}trophyicon.svg';
  static const grid1pic = '${image}mpho-mojapelo-2TCy8pqFXsE-unsplash 1.png';
  static const grid2pic = '${image}image 1.png';
  static const grid3pic = '${image}emil-kalibradov-8WO2s6Yr0Ok-unsplash 1.png';
  static const grid4pic = '${image}agus-donat-Wn_hKtFYgCw-unsplash 1.png';
  static const location = '${image}Location.svg';
  static const home = '${floatingicon}Home.svg';
  static const heart = '${floatingicon}Heart.svg';
  static const message = '${floatingicon}Message.svg';
  static const usericon = '${floatingicon}usericon.svg';
  static const editicon = '${locationicon}Edit.svg';
  static const Locationicon1 = '${locationicon}Locationicon1.svg';
  static const googlemap = '${locationicon}googkemap.png';

  static const service = '${categorypageicon}Service.svg';
  static const communities = '${categorypageicon}communities.svg';
  static const realstate = '${categorypageicon}Real State.svg';
  static const yardsales = '${categorypageicon}Yard Sales.svg';
  static const jobs = '${categorypageicon}jobs.svg';
  static const autoparts = '${categorypageicon}Auto Parts.svg';
  static const children = '${categorypageicon}Children.svg';
  static const boat = '${categorypageicon}boat.svg';
  static const games = '${categorypageicon}games.svg';
  static const speaker = '${categorypageicon}speaker.svg';
  static const vehicles = '${categorypageicon}Vehicles.svg';
  static const jewellery = '${categorypageicon}Jewellery.svg';
  static const antiques = '${categorypageicon}Antiques.svg';
  static const art = '${categorypageicon}Art.svg';
  static const books = '${categorypageicon}books.svg';
  static const chekicon = '${categorypageicon}chekicon.svg';

  static const infomationicon= image + 'infomationicon.svg';
  static const videoicon = image + 'videoicon.svg';
  static const imageicon = image + 'imageicon.svg';
  static const ArrowRight = image + 'Arrow - Right.svg';

}
